/**
 * data.js
 * -----------------------------------------------------------------------
 * Pure content. This is the ONLY file you touch to add sentences.
 * No UI code, no engine code, nothing "smart" lives here — just facts
 * about sentences. lessonEngine, testEngine, progressEngine and every
 * page derive everything else (lesson count, test schedule, progress %)
 * from this array at runtime.
 *
 * To add a sentence: append an object with a new unique id.
 * To add a lesson: use a new `lesson` number — the app notices automatically.
 * To add a language: add a new languageCode block here, and one entry in
 * LANGUAGES (config.js). Nothing else changes.
 *
 * Shape:
 * {
 *   id,              unique integer across the whole language
 *   languageCode,    must match a code in LANGUAGES (config.js)
 *   lesson,          lesson number this sentence belongs to (1-based)
 *   target,          sentence in the target language
 *   pronunciation,   phonetic guide
 *   english,         English translation shown as the prompt
 *   answers          array of accepted spoken/typed answers (gender
 *                    variants, alternate spellings, etc.)
 * }
 */
const SENTENCES = [
  { id: 1,  languageCode: 'es', lesson: 1, target: 'Buenos días',           pronunciation: 'بوينوس دياس',        english: 'Good morning',                answers: ['Buenos días', 'Buenos dias'] },
  { id: 2,  languageCode: 'es', lesson: 1, target: 'Buenas tardes',         pronunciation: 'بويناس تارديس',      english: 'Good afternoon',              answers: ['Buenas tardes'] },
  { id: 3,  languageCode: 'es', lesson: 1, target: 'Buenas noches',         pronunciation: 'بويناس نوتشيس',      english: 'Good evening / night',        answers: ['Buenas noches'] },
  { id: 4,  languageCode: 'es', lesson: 1, target: '¿Cómo estás?',          pronunciation: 'كومو إسطاس',         english: 'How are you?',                answers: ['¿Cómo estás?', 'Como estas', '¿Como estas?'] },
  { id: 5,  languageCode: 'es', lesson: 1, target: 'Estoy bien',            pronunciation: 'إسطوي بيان',         english: 'I am fine',                   answers: ['Estoy bien'] },
  { id: 6,  languageCode: 'es', lesson: 1, target: 'Estoy cansado/a',       pronunciation: 'إسطوي كانسادو',      english: 'I am tired',                  answers: ['Estoy cansado', 'Estoy cansada', 'Estoy cansado/a'] },
  { id: 7,  languageCode: 'es', lesson: 1, target: 'Tengo sueño',           pronunciation: 'تينغو سويينو',       english: 'I am sleepy',                 answers: ['Tengo sueño', 'Tengo sueno'] },
  { id: 8,  languageCode: 'es', lesson: 1, target: 'Tengo hambre',          pronunciation: 'تينغو أمبري',        english: 'I am hungry',                 answers: ['Tengo hambre'] },
  { id: 9,  languageCode: 'es', lesson: 1, target: 'Tengo sed',             pronunciation: 'تينغو سيد',          english: 'I am thirsty',                answers: ['Tengo sed'] },
  { id: 10, languageCode: 'es', lesson: 1, target: 'Necesito descansar',    pronunciation: 'نيسيسيتو ديسكانسار', english: 'I need to rest',               answers: ['Necesito descansar'] },

  { id: 11, languageCode: 'es', lesson: 2, target: 'Me desperté temprano',  pronunciation: 'مي ديسبيرتي تيمبرانو', english: 'I woke up early',            answers: ['Me desperté temprano', 'Me desperte temprano'] },
  { id: 12, languageCode: 'es', lesson: 2, target: 'Voy al trabajo',        pronunciation: 'بوي أل تراباخو',     english: "I'm going to work",           answers: ['Voy al trabajo'] },
  { id: 13, languageCode: 'es', lesson: 2, target: 'Ya llegué',             pronunciation: 'يا ييغي',            english: 'I arrived',                   answers: ['Ya llegué', 'Ya llegue'] },
  { id: 14, languageCode: 'es', lesson: 2, target: 'Estoy ocupado/a',       pronunciation: 'إسطوي أوكوبادو',     english: 'I am busy',                   answers: ['Estoy ocupado', 'Estoy ocupada', 'Estoy ocupado/a'] },
  { id: 15, languageCode: 'es', lesson: 2, target: 'Espera un momento',     pronunciation: 'إسبيرا أون مومينتو', english: 'Wait a moment',               answers: ['Espera un momento'] },
  { id: 16, languageCode: 'es', lesson: 2, target: 'Ahora vuelvo',          pronunciation: 'أورا بويلفو',        english: "I'll be back",                answers: ['Ahora vuelvo'] },
  { id: 17, languageCode: 'es', lesson: 2, target: 'No entiendo',           pronunciation: 'نو إنتييندو',        english: "I don't understand",          answers: ['No entiendo'] },
  { id: 18, languageCode: 'es', lesson: 2, target: 'Entiendo',              pronunciation: 'إنتييندو',           english: 'I understand',                answers: ['Entiendo'] },
  { id: 19, languageCode: 'es', lesson: 2, target: '¿Puedes repetir?',      pronunciation: 'بوديس ريباتير',      english: 'Can you repeat?',             answers: ['¿Puedes repetir?', 'Puedes repetir'] },
  { id: 20, languageCode: 'es', lesson: 2, target: 'Habla más despacio',    pronunciation: 'آبلا ماس ديسباثيو',  english: 'Speak slower',                answers: ['Habla más despacio', 'Habla mas despacio'] },

  { id: 21, languageCode: 'es', lesson: 3, target: '¿Qué pasó?',            pronunciation: 'كي باسو',            english: 'What happened?',              answers: ['¿Qué pasó?', 'Que paso'] },
  { id: 22, languageCode: 'es', lesson: 3, target: 'No pasa nada',          pronunciation: 'نو باسا نادا',       english: "It's okay / Nothing happened", answers: ['No pasa nada'] },
  { id: 23, languageCode: 'es', lesson: 3, target: 'Tengo un error',        pronunciation: 'تينغو أون إيرور',    english: 'I made a mistake',            answers: ['Tengo un error'] },
  { id: 24, languageCode: 'es', lesson: 3, target: 'Me equivoqué',          pronunciation: 'مي إكيوفوكي',        english: 'I was wrong',                 answers: ['Me equivoqué', 'Me equivoque'] },
  { id: 25, languageCode: 'es', lesson: 3, target: 'Lo siento',             pronunciation: 'لو سيينتو',          english: "I'm sorry",                   answers: ['Lo siento'] },
  { id: 26, languageCode: 'es', lesson: 3, target: 'Perdón',                pronunciation: 'بيردون',             english: 'Sorry / Excuse me',           answers: ['Perdón', 'Perdon'] },
  { id: 27, languageCode: 'es', lesson: 3, target: 'Fue mi culpa',          pronunciation: 'فوي مي كولبا',       english: 'It was my fault',             answers: ['Fue mi culpa'] },
  { id: 28, languageCode: 'es', lesson: 3, target: 'No fue mi culpa',       pronunciation: 'نو فوي مي كولبا',    english: "It wasn't my fault",          answers: ['No fue mi culpa'] },
  { id: 29, languageCode: 'es', lesson: 3, target: 'Estoy nervioso/a',      pronunciation: 'إسطوي نيرفيوسّو',    english: 'I am nervous',                answers: ['Estoy nervioso', 'Estoy nerviosa', 'Estoy nervioso/a'] },
  { id: 30, languageCode: 'es', lesson: 3, target: 'Estoy enojado/a',       pronunciation: 'إسطوي إينوخادو',     english: 'I am angry',                  answers: ['Estoy enojado', 'Estoy enojada', 'Estoy enojado/a'] },

  { id: 31, languageCode: 'es', lesson: 4, target: 'Estoy frustrado/a',     pronunciation: 'إسطوي فروسترا دو',   english: 'I am frustrated',             answers: ['Estoy frustrado', 'Estoy frustrada', 'Estoy frustrado/a'] },
  { id: 32, languageCode: 'es', lesson: 4, target: 'Necesito calma',        pronunciation: 'نيسيسيتو كالما',     english: 'I need calm',                 answers: ['Necesito calma'] },
  { id: 33, languageCode: 'es', lesson: 4, target: 'Déjame pensar',         pronunciation: 'ديخامي بينسار',      english: 'Let me think',                answers: ['Déjame pensar', 'Dejame pensar'] },
  { id: 34, languageCode: 'es', lesson: 4, target: 'No estoy de acuerdo',   pronunciation: 'نو إسطوي دي أكويردو', english: "I don't agree",              answers: ['No estoy de acuerdo'] },
  { id: 35, languageCode: 'es', lesson: 4, target: 'Tienes razón',          pronunciation: 'تيينيس راثون',       english: "You're right",                answers: ['Tienes razón', 'Tienes razon'] },
  { id: 36, languageCode: 'es', lesson: 4, target: 'No tienes razón',       pronunciation: 'نو تيينيس راثون',    english: "You're not right",            answers: ['No tienes razón', 'No tienes razon'] },
  { id: 37, languageCode: 'es', lesson: 4, target: 'Qué gracioso',          pronunciation: 'كي غراسيوسو',        english: 'How funny',                   answers: ['Qué gracioso', 'Que gracioso'] },
  { id: 38, languageCode: 'es', lesson: 4, target: 'Me hiciste reír',       pronunciation: 'مي إيستيثتي ريير',   english: 'You made me laugh',           answers: ['Me hiciste reír', 'Me hiciste reir'] },
  { id: 39, languageCode: 'es', lesson: 4, target: 'Estoy feliz',           pronunciation: 'إسطوي فيليس',        english: 'I am happy',                  answers: ['Estoy feliz'] },
  { id: 40, languageCode: 'es', lesson: 4, target: 'Me gusta',              pronunciation: 'مي غوستا',           english: 'I like it',                   answers: ['Me gusta'] },

  { id: 41, languageCode: 'es', lesson: 5, target: 'No me gusta',           pronunciation: 'نو مي غوستا',        english: "I don't like it",             answers: ['No me gusta'] },
  { id: 42, languageCode: 'es', lesson: 5, target: 'Qué interesante',       pronunciation: 'كي إنتيريسانتي',     english: 'How interesting',             answers: ['Qué interesante', 'Que interesante'] },
  { id: 43, languageCode: 'es', lesson: 5, target: 'Tengo mucho trabajo',   pronunciation: 'تينغو موتشو تراباخو', english: 'I have a lot of work',       answers: ['Tengo mucho trabajo'] },
  { id: 44, languageCode: 'es', lesson: 5, target: 'Estoy ocupado hoy',     pronunciation: 'إسطوي أوكوبادو أوي', english: 'I am busy today',             answers: ['Estoy ocupado hoy', 'Estoy ocupada hoy'] },
  { id: 45, languageCode: 'es', lesson: 5, target: 'Necesito ayuda',        pronunciation: 'نيسيسيتو أيودا',     english: 'I need help',                 answers: ['Necesito ayuda'] },
  { id: 46, languageCode: 'es', lesson: 5, target: 'Gracias por tu ayuda',  pronunciation: 'غراسياس بور تو أيودا', english: 'Thanks for your help',      answers: ['Gracias por tu ayuda'] },
  { id: 47, languageCode: 'es', lesson: 5, target: 'No hay problema',       pronunciation: 'نو آي بروبليما',     english: 'No problem',                  answers: ['No hay problema'] },
  { id: 48, languageCode: 'es', lesson: 5, target: 'Todo está bien',        pronunciation: 'تودو إسطا بيان',     english: 'Everything is fine',          answers: ['Todo está bien', 'Todo esta bien'] },
  { id: 49, languageCode: 'es', lesson: 5, target: 'Estoy listo/a',         pronunciation: 'إسطوي ليستو',        english: 'I am ready',                  answers: ['Estoy listo', 'Estoy lista', 'Estoy listo/a'] },
  { id: 50, languageCode: 'es', lesson: 5, target: 'Vamos',                 pronunciation: 'باموس',              english: "Let's go",                    answers: ['Vamos'] },
  { id: 51, languageCode: 'es', lesson: 6, target: 'Acabo de despertarme.', pronunciation: 'أكابو دي ديسبيرتارمي', english: 'I just woke up.', answers: ['Acabo de despertarme.'] },
  { id: 52, languageCode: 'es', lesson: 6, target: 'Voy a lavarme la cara.', pronunciation: 'بوي آ لابارمي لا كارا', english: 'I\'m going to wash my face.', answers: ['Voy a lavarme la cara.'] },
  { id: 53, languageCode: 'es', lesson: 6, target: 'Necesito un café.', pronunciation: 'نيسيسيتو أون كافي', english: 'I need a coffee.', answers: ['Necesito un café.'] },
  { id: 54, languageCode: 'es', lesson: 6, target: 'Hoy tengo mucho que hacer.', pronunciation: 'أوي تينغو موتشو كي آسير', english: 'I have a lot to do today.', answers: ['Hoy tengo mucho que hacer.'] },
  { id: 55, languageCode: 'es', lesson: 6, target: '¿Qué hora es?', pronunciation: 'كي أورا إيس', english: 'What time is it?', answers: ['¿Qué hora es?'] },
  { id: 56, languageCode: 'es', lesson: 6, target: 'Tengo que darme prisa.', pronunciation: 'تينغو كي دارمي بريسا', english: 'I have to hurry.', answers: ['Tengo que darme prisa.'] },
  { id: 57, languageCode: 'es', lesson: 6, target: 'Voy a desayunar.', pronunciation: 'بوي آ ديسايونار', english: 'I\'m going to have breakfast.', answers: ['Voy a desayunar.'] },
  { id: 58, languageCode: 'es', lesson: 6, target: 'Ya estoy despierto/a.', pronunciation: 'يا إسطوي ديسبييرتو', english: 'I\'m already awake.', answers: ['Ya estoy despierto', 'Ya estoy despierta'] },
  { id: 59, languageCode: 'es', lesson: 6, target: 'Hoy me siento bien.', pronunciation: 'أوي مي سيينتو بيان', english: 'I feel good today.', answers: ['Hoy me siento bien.'] },
  { id: 60, languageCode: 'es', lesson: 6, target: 'No quiero levantarme.', pronunciation: 'نو كييرو ليبانتارمي', english: 'I don\'t want to get up.', answers: ['No quiero levantarme.'] },
  { id: 61, languageCode: 'es', lesson: 7, target: 'Voy a empezar a trabajar.', pronunciation: 'بوي آ إمبيثار آ تراباخار', english: 'I\'m going to start working.', answers: ['Voy a empezar a trabajar.'] },
  { id: 62, languageCode: 'es', lesson: 7, target: 'Estoy concentrado/a.', pronunciation: 'إسطوي كونسينترادو', english: 'I\'m focused.', answers: ['Estoy concentrado', 'Estoy concentrada'] },
  { id: 63, languageCode: 'es', lesson: 7, target: 'Necesito terminar esto.', pronunciation: 'نيسيسيتو تيرمينار إسطو', english: 'I need to finish this.', answers: ['Necesito terminar esto.'] },
  { id: 64, languageCode: 'es', lesson: 7, target: 'Lo haré después.', pronunciation: 'لو آري ديسبويس', english: 'I\'ll do it later.', answers: ['Lo haré después.'] },
  { id: 65, languageCode: 'es', lesson: 7, target: 'Estoy haciendo lo mejor que puedo.', pronunciation: 'إسطوي آسييندو لو ميخور كي بودو', english: 'I\'m doing the best I can.', answers: ['Estoy haciendo lo mejor que puedo.'] },
  { id: 66, languageCode: 'es', lesson: 7, target: 'Dame cinco minutos.', pronunciation: 'دامي سينكو مينوتوس', english: 'Give me five minutes.', answers: ['Dame cinco minutos.'] },
  { id: 67, languageCode: 'es', lesson: 7, target: 'Ya casi termino.', pronunciation: 'يا كاسي تيرمينو', english: 'I\'m almost finished.', answers: ['Ya casi termino.'] },
  { id: 68, languageCode: 'es', lesson: 7, target: 'Esto es más difícil de lo que pensaba.', pronunciation: 'إسطو إيس ماس ديفيسيل دي لو كي بينسابا', english: 'This is harder than I thought.', answers: ['Esto es más difícil de lo que pensaba.'] },
  { id: 69, languageCode: 'es', lesson: 7, target: 'Tengo que concentrarme.', pronunciation: 'تينغو كي كونسينترارمي', english: 'I have to concentrate.', answers: ['Tengo que concentrarme.'] },
  { id: 70, languageCode: 'es', lesson: 7, target: 'Necesito un descanso.', pronunciation: 'نيسيسيتو أون ديسكانسو', english: 'I need a break.', answers: ['Necesito un descanso.'] },
  { id: 71, languageCode: 'es', lesson: 8, target: 'Estoy agotado/a.', pronunciation: 'إسطوي أغوتادو', english: 'I\'m exhausted.', answers: ['Estoy agotado', 'Estoy agotada'] },
  { id: 72, languageCode: 'es', lesson: 8, target: 'Hoy ha sido un día largo.', pronunciation: 'أوي آ سيدو أون ديا لارغو', english: 'Today has been a long day.', answers: ['Hoy ha sido un día largo.'] },
  { id: 73, languageCode: 'es', lesson: 8, target: 'No tengo energía.', pronunciation: 'نو تينغو إينيرخيا', english: 'I have no energy.', answers: ['No tengo energía.'] },
  { id: 74, languageCode: 'es', lesson: 8, target: 'Quiero irme a casa.', pronunciation: 'كييرو إيرمي آ كاسا', english: 'I want to go home.', answers: ['Quiero irme a casa.'] },
  { id: 75, languageCode: 'es', lesson: 8, target: 'Necesito dormir.', pronunciation: 'نيسيسيتو دورمير', english: 'I need to sleep.', answers: ['Necesito dormir.'] },
  { id: 76, languageCode: 'es', lesson: 8, target: 'Voy a descansar un poco.', pronunciation: 'بوي آ ديسكانسار أون بوكو', english: 'I\'m going to rest a little.', answers: ['Voy a descansar un poco.'] },
  { id: 77, languageCode: 'es', lesson: 8, target: 'Estoy demasiado cansado/a.', pronunciation: 'إسطوي ديمسيادو كانسادو', english: 'I\'m too tired.', answers: ['Estoy demasiado cansado', 'Estoy demasiado cansada'] },
  { id: 78, languageCode: 'es', lesson: 8, target: 'No puedo mantener los ojos abiertos.', pronunciation: 'نو بويدو مانتينير لوس أوخوس أبييرتوس', english: 'I can\'t keep my eyes open.', answers: ['No puedo mantener los ojos abiertos.'] },
  { id: 79, languageCode: 'es', lesson: 8, target: 'Me voy a dormir.', pronunciation: 'مي بوي آ دورمير', english: 'I\'m going to sleep.', answers: ['Me voy a dormir.'] },
  { id: 80, languageCode: 'es', lesson: 8, target: 'Buenas noches, que descanses.', pronunciation: 'بويناس نوتشيس، كي ديسكانسيس', english: 'Good night, sleep well.', answers: ['Buenas noches, que descanses.'] },
  { id: 81, languageCode: 'es', lesson: 9, target: '¡No puedo parar de reír!', pronunciation: 'نو بويدو بارار دي ريير', english: 'I can\'t stop laughing!', answers: ['¡No puedo parar de reír!'] },
  { id: 82, languageCode: 'es', lesson: 9, target: '¡Qué divertido!', pronunciation: 'كي ديفيرتيدو', english: 'How funny!', answers: ['¡Qué divertido!'] },
  { id: 83, languageCode: 'es', lesson: 9, target: '¡Estás loco/a!', pronunciation: 'إسطاس لوكو', english: 'You\'re crazy!', answers: ['Estás loco', 'Estás loca'] },
  { id: 84, languageCode: 'es', lesson: 9, target: 'No puedo creerlo.', pronunciation: 'نو بويدو كريرلو', english: 'I can\'t believe it.', answers: ['No puedo creerlo.'] },
  { id: 85, languageCode: 'es', lesson: 9, target: 'Eso fue muy gracioso.', pronunciation: 'إيسو فوي موي غراسيوسو', english: 'That was really funny.', answers: ['Eso fue muy gracioso.'] },
  { id: 86, languageCode: 'es', lesson: 9, target: '¿Estás hablando en serio?', pronunciation: 'إسطاس أبلاندو إن سيريو', english: 'Are you serious?', answers: ['¿Estás hablando en serio?'] },
  { id: 87, languageCode: 'es', lesson: 9, target: '¡No me hagas reír!', pronunciation: 'نو مي أغاس ريير', english: 'Don\'t make me laugh!', answers: ['¡No me hagas reír!'] },
  { id: 88, languageCode: 'es', lesson: 9, target: 'Qué buena idea.', pronunciation: 'كي بوينا إيديا', english: 'What a good idea.', answers: ['Qué buena idea.'] },
  { id: 89, languageCode: 'es', lesson: 9, target: 'Me encanta esto.', pronunciation: 'مي إنكانتا إسطو', english: 'I love this.', answers: ['Me encanta esto.'] },
  { id: 90, languageCode: 'es', lesson: 9, target: 'Eso tiene sentido.', pronunciation: 'إيسو تييني سينتيدو', english: 'That makes sense.', answers: ['Eso tiene sentido.'] },
  { id: 91, languageCode: 'es', lesson: 10, target: 'Estoy harto/a de esto.', pronunciation: 'إسطوي آرتو دي إسطو', english: 'I\'m fed up with this.', answers: ['Estoy harto de esto', 'Estoy harta de esto'] },
  { id: 92, languageCode: 'es', lesson: 10, target: '¡Déjame en paz!', pronunciation: 'ديخامي إن باث', english: 'Leave me alone!', answers: ['¡Déjame en paz!'] },
  { id: 93, languageCode: 'es', lesson: 10, target: 'No me molestes.', pronunciation: 'نو مي مولستيس', english: 'Don\'t bother me.', answers: ['No me molestes.'] },
  { id: 94, languageCode: 'es', lesson: 10, target: 'Necesito tranquilizarme.', pronunciation: 'نيسيسيتو ترانكيليثارمي', english: 'I need to calm down.', answers: ['Necesito tranquilizarme.'] },
  { id: 95, languageCode: 'es', lesson: 10, target: 'Cometí un error.', pronunciation: 'كومِتي أون إيرور', english: 'I made a mistake.', answers: ['Cometí un error.'] },
  { id: 96, languageCode: 'es', lesson: 10, target: 'No lo hice a propósito.', pronunciation: 'نو لو إيسي آ بروسيتو', english: 'I didn\'t do it on purpose.', answers: ['No lo hice a propósito.'] },
  { id: 97, languageCode: 'es', lesson: 10, target: 'Lo hice mal.', pronunciation: 'لو إيسي مال', english: 'I did it wrong.', answers: ['Lo hice mal.'] },
  { id: 98, languageCode: 'es', lesson: 10, target: 'Voy a intentarlo otra vez.', pronunciation: 'بوي آ إنتينتارلو أوترا بيث', english: 'I\'ll try it again.', answers: ['Voy a intentarlo otra vez.'] },
  { id: 99, languageCode: 'es', lesson: 10, target: 'La próxima vez lo haré mejor.', pronunciation: 'لا بروكسِيما بيث لو آري ميخور', english: 'I\'ll do better next time.', answers: ['La próxima vez lo haré mejor.'] },
  { id: 100, languageCode: 'es', lesson: 10, target: 'No te preocupes, ya está.', pronunciation: 'نو تي بريوكوبِس، يا إسطا', english: 'Don\'t worry, it\'s okay now.', answers: ['No te preocupes, ya está.'] },
  { id: 101, languageCode: 'es', lesson: 11, target: '¿Qué estás haciendo?', pronunciation: 'كي إسطاس آسييندو', english: 'What are you doing?', answers: ['¿Qué estás haciendo?'] },
  { id: 102, languageCode: 'es', lesson: 11, target: 'Estoy preparando la comida.', pronunciation: 'إسطوي بريبَراندو لا كوميدا', english: 'I\'m preparing food.', answers: ['Estoy preparando la comida.'] },
  { id: 103, languageCode: 'es', lesson: 11, target: 'Ya comí.', pronunciation: 'يا كومي', english: 'I already ate.', answers: ['Ya comí.'] },
  { id: 104, languageCode: 'es', lesson: 11, target: 'Voy a comer algo.', pronunciation: 'بوي آ كومير ألغو', english: 'I\'m going to eat something.', answers: ['Voy a comer algo.'] },
  { id: 105, languageCode: 'es', lesson: 11, target: '¿Quieres comer conmigo?', pronunciation: 'كييريس كومير كونميغو', english: 'Do you want to eat with me?', answers: ['¿Quieres comer conmigo?'] },
  { id: 106, languageCode: 'es', lesson: 11, target: 'No tengo ganas de salir.', pronunciation: 'نو تينغو غاناس دي سالير', english: 'I don\'t feel like going out.', answers: ['No tengo ganas de salir.'] },
  { id: 107, languageCode: 'es', lesson: 11, target: 'Vamos a dar una vuelta.', pronunciation: 'باموس آ دار أونا بويلتا', english: 'Let\'s go for a walk.', answers: ['Vamos a dar una vuelta.'] },
  { id: 108, languageCode: 'es', lesson: 11, target: 'Estoy en camino.', pronunciation: 'إسطوي إن كامينو', english: 'I\'m on my way.', answers: ['Estoy en camino.'] },
  { id: 109, languageCode: 'es', lesson: 11, target: 'Llegaré pronto.', pronunciation: 'ييغاري برونتو', english: 'I\'ll arrive soon.', answers: ['Llegaré pronto.'] },
  { id: 110, languageCode: 'es', lesson: 11, target: 'Espérame aquí.', pronunciation: 'إسبيرامي أكي', english: 'Wait for me here.', answers: ['Espérame aquí.'] },
  { id: 111, languageCode: 'es', lesson: 12, target: '¿Dónde estás?', pronunciation: 'دوندي إسطاس', english: 'Where are you?', answers: ['¿Dónde estás?'] },
  { id: 112, languageCode: 'es', lesson: 12, target: 'Estoy en casa.', pronunciation: 'إسطوي إن كاسا', english: 'I\'m at home.', answers: ['Estoy en casa.'] },
  { id: 113, languageCode: 'es', lesson: 12, target: 'Salgo en cinco minutos.', pronunciation: 'سالغو إن سينكو مينوتوس', english: 'I\'m leaving in five minutes.', answers: ['Salgo en cinco minutos.'] },
  { id: 114, languageCode: 'es', lesson: 12, target: 'No encuentro mis llaves.', pronunciation: 'نو إنكوينترو ميس يابيس', english: 'I can\'t find my keys.', answers: ['No encuentro mis llaves.'] },
  { id: 115, languageCode: 'es', lesson: 12, target: '¿Has visto mi teléfono?', pronunciation: 'آس بيستو مي تيليفونو', english: 'Have you seen my phone?', answers: ['¿Has visto mi teléfono?'] },
  { id: 116, languageCode: 'es', lesson: 12, target: 'Mi teléfono está sin batería.', pronunciation: 'مي تيليفونو إسطا سين باتيريا', english: 'My phone has no battery.', answers: ['Mi teléfono está sin batería.'] },
  { id: 117, languageCode: 'es', lesson: 12, target: 'Te llamo más tarde.', pronunciation: 'تي يامو ماس تاردي', english: 'I\'ll call you later.', answers: ['Te llamo más tarde.'] },
  { id: 118, languageCode: 'es', lesson: 12, target: 'Escríbeme cuando llegues.', pronunciation: 'إسكريبيمي كواندو ييغيس', english: 'Text me when you arrive.', answers: ['Escríbeme cuando llegues.'] },
  { id: 119, languageCode: 'es', lesson: 12, target: 'Ahora no puedo hablar.', pronunciation: 'أورا نو بويدو أبلار', english: 'I can\'t talk right now.', answers: ['Ahora no puedo hablar.'] },
  { id: 120, languageCode: 'es', lesson: 12, target: 'Estoy un poco ocupado.', pronunciation: 'إسطوي أون بوكو أوكوبادو', english: 'I\'m a little busy.', answers: ['Estoy un poco ocupado.'] },
  { id: 121, languageCode: 'es', lesson: 13, target: 'Dame un segundo.', pronunciation: 'دامي أون سيغوندو', english: 'Give me a second.', answers: ['Dame un segundo.'] },
  { id: 122, languageCode: 'es', lesson: 13, target: 'Espera, estoy pensando.', pronunciation: 'إسبيرا، إسطوي بينساندو', english: 'Wait, I\'m thinking.', answers: ['Espera, estoy pensando.'] },
  { id: 123, languageCode: 'es', lesson: 13, target: 'Déjame comprobarlo.', pronunciation: 'ديخامي كومبروبَارلو', english: 'Let me check it.', answers: ['Déjame comprobarlo.'] },
  { id: 124, languageCode: 'es', lesson: 13, target: 'Voy a buscarlo.', pronunciation: 'بوي آ بوسكارلو', english: 'I\'m going to look for it.', answers: ['Voy a buscarlo.'] },
  { id: 125, languageCode: 'es', lesson: 13, target: 'Ya lo encontré.', pronunciation: 'يا لو إنكونتري', english: 'I found it.', answers: ['Ya lo encontré.'] },
  { id: 126, languageCode: 'es', lesson: 13, target: 'No lo sé todavía.', pronunciation: 'نو لو سي تودابيا', english: 'I don\'t know yet.', answers: ['No lo sé todavía.'] },
  { id: 127, languageCode: 'es', lesson: 13, target: 'Lo pensaré.', pronunciation: 'لو بينساري', english: 'I\'ll think about it.', answers: ['Lo pensaré.'] },
  { id: 128, languageCode: 'es', lesson: 13, target: 'Tengo una idea.', pronunciation: 'تينغو أونا إيديا', english: 'I have an idea.', answers: ['Tengo una idea.'] },
  { id: 129, languageCode: 'es', lesson: 13, target: 'Creo que sí.', pronunciation: 'كريو كي سي', english: 'I think so.', answers: ['Creo que sí.'] },
  { id: 130, languageCode: 'es', lesson: 13, target: 'Creo que no.', pronunciation: 'كريو كي نو', english: 'I don\'t think so.', answers: ['Creo que no.'] },
  { id: 131, languageCode: 'es', lesson: 14, target: 'Tal vez tengas razón.', pronunciation: 'تال بيث تينغاس راثون', english: 'Maybe you\'re right.', answers: ['Tal vez tengas razón.'] },
  { id: 132, languageCode: 'es', lesson: 14, target: 'No estoy seguro/a.', pronunciation: 'نو إسطوي سيغورو', english: 'I\'m not sure.', answers: ['No estoy seguro', 'No estoy segura'] },
  { id: 133, languageCode: 'es', lesson: 14, target: 'Depende de la situación.', pronunciation: 'ديبيندي دي لا سيتواثيون', english: 'It depends on the situation.', answers: ['Depende de la situación.'] },
  { id: 134, languageCode: 'es', lesson: 14, target: 'Eso no importa.', pronunciation: 'إيسو نو إمبورتا', english: 'That doesn\'t matter.', answers: ['Eso no importa.'] },
  { id: 135, languageCode: 'es', lesson: 14, target: 'Me da igual.', pronunciation: 'مي دا إيغوال', english: 'I don\'t mind / It\'s all the same to me.', answers: ['Me da igual.'] },
  { id: 136, languageCode: 'es', lesson: 14, target: 'No me importa.', pronunciation: 'نو مي إمبورتا', english: 'I don\'t care.', answers: ['No me importa.'] },
  { id: 137, languageCode: 'es', lesson: 14, target: 'Tienes que tener paciencia.', pronunciation: 'تيينيس كي تينير باسيينسيا', english: 'You have to be patient.', answers: ['Tienes que tener paciencia.'] },
  { id: 138, languageCode: 'es', lesson: 14, target: 'Todo lleva tiempo.', pronunciation: 'تودو ييبا تييمبو', english: 'Everything takes time.', answers: ['Todo lleva tiempo.'] },
  { id: 139, languageCode: 'es', lesson: 14, target: 'Voy a intentarlo.', pronunciation: 'بوي آ إنتينتارلو', english: 'I\'m going to try.', answers: ['Voy a intentarlo.'] },
  { id: 140, languageCode: 'es', lesson: 14, target: 'No quiero rendirme.', pronunciation: 'نو كييرو رينديرمي', english: 'I don\'t want to give up.', answers: ['No quiero rendirme.'] },
  { id: 141, languageCode: 'es', lesson: 15, target: 'Casi me olvido.', pronunciation: 'كاسي مي أولبيدو', english: 'I almost forgot.', answers: ['Casi me olvido.'] },
  { id: 142, languageCode: 'es', lesson: 15, target: 'Se me olvidó.', pronunciation: 'سي مي أولبيدو', english: 'I forgot.', answers: ['Se me olvidó.'] },
  { id: 143, languageCode: 'es', lesson: 15, target: 'Lo recuerdo ahora.', pronunciation: 'لو ريكويردو أورا', english: 'I remember now.', answers: ['Lo recuerdo ahora.'] },
  { id: 144, languageCode: 'es', lesson: 15, target: 'No era eso lo que quería decir.', pronunciation: 'نو إيرا إيسو لو كي كيريا ديسير', english: 'That\'s not what I meant.', answers: ['No era eso lo que quería decir.'] },
  { id: 145, languageCode: 'es', lesson: 15, target: 'Me expliqué mal.', pronunciation: 'مي إكسبليكي مال', english: 'I explained myself badly.', answers: ['Me expliqué mal.'] },
  { id: 146, languageCode: 'es', lesson: 15, target: 'Déjame explicarte.', pronunciation: 'ديخامي إكسبليكارتي', english: 'Let me explain to you.', answers: ['Déjame explicarte.'] },
  { id: 147, languageCode: 'es', lesson: 15, target: 'No quería hacerlo así.', pronunciation: 'نو كيريا آثيرلو آسي', english: 'I didn\'t want to do it like that.', answers: ['No quería hacerlo así.'] },
  { id: 148, languageCode: 'es', lesson: 15, target: 'Ya aprendí la lección.', pronunciation: 'يا أبريندي لا ليكسيون', english: 'I learned my lesson.', answers: ['Ya aprendí la lección.'] },
  { id: 149, languageCode: 'es', lesson: 15, target: 'Mañana será otro día.', pronunciation: 'مانيانا سيرا أوترو ديا', english: 'Tomorrow is another day.', answers: ['Mañana será otro día.'] },
  { id: 150, languageCode: 'es', lesson: 15, target: 'Voy a dormir, hablamos mañana.', pronunciation: 'بوي آ دورمير، أبلاموس مانيانا', english: 'I\'m going to sleep, we\'ll talk tomorrow.', answers: ['Voy a dormir, hablamos mañana.'] },
  { id: 151, languageCode: 'es', lesson: 16, target: '¿Dónde está el aeropuerto?', pronunciation: 'دوندي إستا إل أيروبويرتو', english: 'Where is the airport?', answers: ['¿Dónde está el aeropuerto?'] },
  { id: 152, languageCode: 'es', lesson: 16, target: '¿Cuánto cuesta el billete?', pronunciation: 'كوانتو كويستا إل بيييتي', english: 'How much is the ticket?', answers: ['¿Cuánto cuesta el billete?'] },
  { id: 153, languageCode: 'es', lesson: 16, target: 'Tengo una reserva.', pronunciation: 'تينغو أونا ريسيربا', english: 'I have a reservation.', answers: ['Tengo una reserva.'] },
  { id: 154, languageCode: 'es', lesson: 16, target: '¿A qué hora sale el avión?', pronunciation: 'آ كي أورا سالي إل أبيون', english: 'What time does the plane leave?', answers: ['¿A qué hora sale el avión?'] },
  { id: 155, languageCode: 'es', lesson: 16, target: '¿Dónde puedo comprar una tarjeta SIM?', pronunciation: 'دوندي بويذو كومبرار أونا تارخيتا سيم', english: 'Where can I buy a SIM card?', answers: ['¿Dónde puedo comprar una tarjeta SIM?'] },
  { id: 156, languageCode: 'es', lesson: 16, target: '¿Puedes ayudarme con mi maleta?', pronunciation: 'بويذيس أيودارمي كون مي ماليطا', english: 'Can you help me with my suitcase?', answers: ['¿Puedes ayudarme con mi maleta?'] },
  { id: 157, languageCode: 'es', lesson: 16, target: 'Me he perdido.', pronunciation: 'مي إي بيرديدو', english: 'I\'m lost.', answers: ['Me he perdido.'] },
  { id: 158, languageCode: 'es', lesson: 16, target: '¿Está lejos de aquí?', pronunciation: 'إستا ليخوس دي أكي', english: 'Is it far from here?', answers: ['¿Está lejos de aquí?'] },
  { id: 159, languageCode: 'es', lesson: 16, target: 'Quiero ir a este lugar.', pronunciation: 'كييرو إير آ إستي لوغار', english: 'I want to go to this place.', answers: ['Quiero ir a este lugar.'] },
  { id: 160, languageCode: 'es', lesson: 16, target: '¿Puedes decirme cómo llegar?', pronunciation: 'بويذيس ذيسيرمي كومو ييگار', english: 'Can you tell me how to get there?', answers: ['¿Puedes decirme cómo llegar?'] },
  { id: 161, languageCode: 'es', lesson: 17, target: 'Tengo que estudiar hoy.', pronunciation: 'تينغو كي إستوديار أوي', english: 'I have to study today.', answers: ['Tengo que estudiar hoy.'] },
  { id: 162, languageCode: 'es', lesson: 17, target: 'No entiendo esta parte.', pronunciation: 'نو إنتييندو إستا بارتي', english: 'I don\'t understand this part.', answers: ['No entiendo esta parte.'] },
  { id: 163, languageCode: 'es', lesson: 17, target: '¿Puedes explicármelo otra vez?', pronunciation: 'بويذيس إكسبليكارميلو أوترا بيث', english: 'Can you explain it again?', answers: ['¿Puedes explicármelo otra vez?'] },
  { id: 164, languageCode: 'es', lesson: 17, target: 'Necesito más tiempo.', pronunciation: 'نيسيسيتو ماس تييمبو', english: 'I need more time.', answers: ['Necesito más tiempo.'] },
  { id: 165, languageCode: 'es', lesson: 17, target: 'Voy a estudiar una hora.', pronunciation: 'بوي آ إستوديار أونا أورا', english: 'I\'m going to study for an hour.', answers: ['Voy a estudiar una hora.'] },
  { id: 166, languageCode: 'es', lesson: 17, target: 'Tengo un examen mañana.', pronunciation: 'تينغو أون إكزامين مانيانا', english: 'I have an exam tomorrow.', answers: ['Tengo un examen mañana.'] },
  { id: 167, languageCode: 'es', lesson: 17, target: 'Tengo que terminar esto.', pronunciation: 'تينغو كي تيرمينار إستو', english: 'I have to finish this.', answers: ['Tengo que terminar esto.'] },
  { id: 168, languageCode: 'es', lesson: 17, target: 'Voy a tomar un descanso.', pronunciation: 'بوي آ تومار أون ديسكانسو', english: 'I\'m going to take a break.', answers: ['Voy a tomar un descanso.'] },
  { id: 169, languageCode: 'es', lesson: 17, target: 'Hoy aprendí algo nuevo.', pronunciation: 'أوي أبريندي ألگو نويبو', english: 'I learned something new today.', answers: ['Hoy aprendí algo nuevo.'] },
  { id: 170, languageCode: 'es', lesson: 17, target: 'Necesito concentrarme.', pronunciation: 'نيسيسيتو كونسينترارمي', english: 'I need to concentrate.', answers: ['Necesito concentrarme.'] },
  { id: 171, languageCode: 'es', lesson: 18, target: 'Voy a limpiar mi habitación.', pronunciation: 'بوي آ ليمبيار مي أبيتاثيون', english: 'I\'m going to clean my room.', answers: ['Voy a limpiar mi habitación.'] },
  { id: 172, languageCode: 'es', lesson: 18, target: 'Tengo que ordenar la casa.', pronunciation: 'تينغو كي أوردينار لا كاسا', english: 'I have to tidy the house.', answers: ['Tengo que ordenar la casa.'] },
  { id: 173, languageCode: 'es', lesson: 18, target: '¿Dónde está la escoba?', pronunciation: 'دوندي إستا لا إسكوبا', english: 'Where is the broom?', answers: ['¿Dónde está la escoba?'] },
  { id: 174, languageCode: 'es', lesson: 18, target: 'Voy a lavar los platos.', pronunciation: 'بوي آ لابار لوس بلاتوس', english: 'I\'m going to wash the dishes.', answers: ['Voy a lavar los platos.'] },
  { id: 175, languageCode: 'es', lesson: 18, target: 'La ropa está sucia.', pronunciation: 'لا روبا إستا سوسيا', english: 'The clothes are dirty.', answers: ['La ropa está sucia.'] },
  { id: 176, languageCode: 'es', lesson: 18, target: 'Tengo que lavar la ropa.', pronunciation: 'تينغو كي لابار لا روبا', english: 'I have to do the laundry.', answers: ['Tengo que lavar la ropa.'] },
  { id: 177, languageCode: 'es', lesson: 18, target: 'Abre la ventana, por favor.', pronunciation: 'أبري لا بينتانا، بور فابور', english: 'Open the window, please.', answers: ['Abre la ventana, por favor.'] },
  { id: 178, languageCode: 'es', lesson: 18, target: 'Cierra la puerta.', pronunciation: 'ثييرا لا بويرتا', english: 'Close the door.', answers: ['Cierra la puerta.'] },
  { id: 179, languageCode: 'es', lesson: 18, target: 'Voy a preparar algo de comer.', pronunciation: 'بوي آ بريبَرار ألغو دي كومير', english: 'I\'m going to make something to eat.', answers: ['Voy a preparar algo de comer.'] },
  { id: 180, languageCode: 'es', lesson: 18, target: 'La casa está muy desordenada.', pronunciation: 'لا كاسا إستا موي ديسورذينادا', english: 'The house is very messy.', answers: ['La casa está muy desordenada.'] },
  { id: 181, languageCode: 'es', lesson: 19, target: 'Tengo mucha hambre.', pronunciation: 'تينغو موتشا أمبري', english: 'I\'m very hungry.', answers: ['Tengo mucha hambre.'] },
  { id: 182, languageCode: 'es', lesson: 19, target: '¿Me traes el menú, por favor?', pronunciation: 'مي ترايس إل مينّو، بور فابور', english: 'Can you bring me the menu, please?', answers: ['¿Me traes el menú, por favor?'] },
  { id: 183, languageCode: 'es', lesson: 19, target: 'Quiero pedir esto.', pronunciation: 'كييرو بيدير إستو', english: 'I want to order this.', answers: ['Quiero pedir esto.'] },
  { id: 184, languageCode: 'es', lesson: 19, target: '¿Qué me recomiendas?', pronunciation: 'كي مي ريكوميينداس', english: 'What do you recommend?', answers: ['¿Qué me recomiendas?'] },
  { id: 185, languageCode: 'es', lesson: 19, target: 'Quiero algo ligero.', pronunciation: 'كييرو ألغو ليخيرو', english: 'I want something light.', answers: ['Quiero algo ligero.'] },
  { id: 186, languageCode: 'es', lesson: 19, target: 'Sin cebolla, por favor.', pronunciation: 'سين ثيبويّا، بور فابور', english: 'No onion, please.', answers: ['Sin cebolla, por favor.'] },
  { id: 187, languageCode: 'es', lesson: 19, target: '¿Esto es picante?', pronunciation: 'إستو إس بيكانتي', english: 'Is this spicy?', answers: ['¿Esto es picante?'] },
  { id: 188, languageCode: 'es', lesson: 19, target: 'Está muy rico.', pronunciation: 'إستا موي ريكو', english: 'It\'s very tasty.', answers: ['Está muy rico.'] },
  { id: 189, languageCode: 'es', lesson: 19, target: 'La comida está fría.', pronunciation: 'لا كوميدا إستا فريا', english: 'The food is cold.', answers: ['La comida está fría.'] },
  { id: 190, languageCode: 'es', lesson: 19, target: '¿Me traes la cuenta?', pronunciation: 'مي ترايس لا كوينتا', english: 'Can you bring me the bill?', answers: ['¿Me traes la cuenta?'] },
  { id: 191, languageCode: 'es', lesson: 20, target: 'Me acabo de despertar.', pronunciation: 'مي أكابو دي ديسبيرتار', english: 'I just woke up.', answers: ['Me acabo de despertar.'] },
  { id: 192, languageCode: 'es', lesson: 20, target: 'Voy a ducharme.', pronunciation: 'بوي آ دوچَارمي', english: 'I\'m going to take a shower.', answers: ['Voy a ducharme.'] },
  { id: 193, languageCode: 'es', lesson: 20, target: 'Tengo que vestirme.', pronunciation: 'تينغو كي بيستيرمي', english: 'I have to get dressed.', answers: ['Tengo que vestirme.'] },
  { id: 194, languageCode: 'es', lesson: 20, target: 'Voy a preparar el desayuno.', pronunciation: 'بوي آ بريبَرار إل ديسايونو', english: 'I\'m going to make breakfast.', answers: ['Voy a preparar el desayuno.'] },
  { id: 195, languageCode: 'es', lesson: 20, target: 'Hoy tengo mucho que hacer.', pronunciation: 'أوي تينغو موتشو كي أسير', english: 'I have a lot to do today.', answers: ['Hoy tengo mucho que hacer.'] },
  { id: 196, languageCode: 'es', lesson: 20, target: 'Primero voy a terminar esto.', pronunciation: 'بريميرو بوي آ تيرمينار إستو', english: 'First, I\'m going to finish this.', answers: ['Primero voy a terminar esto.'] },
  { id: 197, languageCode: 'es', lesson: 20, target: 'Después voy a salir.', pronunciation: 'ديسبويس بوي آ سالير', english: 'Then I\'m going to go out.', answers: ['Después voy a salir.'] },
  { id: 198, languageCode: 'es', lesson: 20, target: 'Estoy cansado, necesito descansar.', pronunciation: 'إستوي كانسادو، نيسيسيتو ديسكانسار', english: 'I\'m tired, I need to rest.', answers: ['Estoy cansado, necesito descansar.'] },
  { id: 199, languageCode: 'es', lesson: 20, target: 'Ya es hora de dormir.', pronunciation: 'يا إس أورا دي دورمير', english: 'It\'s time to sleep.', answers: ['Ya es hora de dormir.'] },
  { id: 200, languageCode: 'es', lesson: 20, target: 'Buenas noches, hasta mañana.', pronunciation: 'بويناس نوتشيس، أستا مانيانا', english: 'Good night, see you tomorrow.', answers: ['Buenas noches, hasta mañana.'] },
  { id: 201, languageCode: 'es', lesson: 21, target: '¿Dónde puedo encontrar esto?', pronunciation: 'دوندي بويذو إنكونترار إستو', english: 'Where can I find this?', answers: ['¿Dónde puedo encontrar esto?'] },
  { id: 202, languageCode: 'es', lesson: 21, target: '¿Cuánto cuesta esto?', pronunciation: 'كوانتو كويستا إستو', english: 'How much does this cost?', answers: ['¿Cuánto cuesta esto?'] },
  { id: 203, languageCode: 'es', lesson: 21, target: 'Es demasiado caro.', pronunciation: 'إس دِماسيادو كارو', english: 'It\'s too expensive.', answers: ['Es demasiado caro.'] },
  { id: 204, languageCode: 'es', lesson: 21, target: '¿Tienes algo más barato?', pronunciation: 'تيينيس ألغو ماس باراتو', english: 'Do you have something cheaper?', answers: ['¿Tienes algo más barato?'] },
  { id: 205, languageCode: 'es', lesson: 21, target: 'Solo estoy mirando.', pronunciation: 'سولو إستوي ميراندو', english: 'I\'m just looking.', answers: ['Solo estoy mirando.'] },
  { id: 206, languageCode: 'es', lesson: 21, target: 'Quiero comprar esto.', pronunciation: 'كييرو كومبرار إستو', english: 'I want to buy this.', answers: ['Quiero comprar esto.'] },
  { id: 207, languageCode: 'es', lesson: 21, target: '¿Puedo pagar con tarjeta?', pronunciation: 'بويذو باغار كون تارخيتا', english: 'Can I pay by card?', answers: ['¿Puedo pagar con tarjeta?'] },
  { id: 208, languageCode: 'es', lesson: 21, target: 'No tengo efectivo.', pronunciation: 'نو تينغو إيفيكتِيبو', english: 'I don\'t have cash.', answers: ['No tengo efectivo.'] },
  { id: 209, languageCode: 'es', lesson: 21, target: '¿Me puedes dar una bolsa?', pronunciation: 'مي بويذيس دار أونا بولسا', english: 'Can you give me a bag?', answers: ['¿Me puedes dar una bolsa?'] },
  { id: 210, languageCode: 'es', lesson: 21, target: 'Necesito cambiar esto.', pronunciation: 'نيسيسيتو كامبيار إستو', english: 'I need to exchange this.', answers: ['Necesito cambiar esto.'] },
  { id: 211, languageCode: 'es', lesson: 22, target: '¿Dónde está la estación?', pronunciation: 'دوندي إستا لا إستاثيون', english: 'Where is the station?', answers: ['¿Dónde está la estación?'] },
  { id: 212, languageCode: 'es', lesson: 22, target: '¿Este autobús va al centro?', pronunciation: 'إستي أوتوبوس با آل ثينترو', english: 'Does this bus go downtown?', answers: ['¿Este autobús va al centro?'] },
  { id: 213, languageCode: 'es', lesson: 22, target: '¿Cuándo llega el tren?', pronunciation: 'كواندو ييغا إل ترين', english: 'When does the train arrive?', answers: ['¿Cuándo llega el tren?'] },
  { id: 214, languageCode: 'es', lesson: 22, target: 'Necesito un taxi.', pronunciation: 'نيسيسيتو أون تاكسي', english: 'I need a taxi.', answers: ['Necesito un taxi.'] },
  { id: 215, languageCode: 'es', lesson: 22, target: 'Déjame aquí, por favor.', pronunciation: 'ديخامِ أكي، بور فابور', english: 'Drop me off here, please.', answers: ['Déjame aquí, por favor.'] },
  { id: 216, languageCode: 'es', lesson: 22, target: '¿Cuánto tardamos?', pronunciation: 'كوانتو تارداموس', english: 'How long will it take?', answers: ['¿Cuánto tardamos?'] },
  { id: 217, languageCode: 'es', lesson: 22, target: 'Voy un poco tarde.', pronunciation: 'بوي أون بوكو تاردي', english: 'I\'m a little late.', answers: ['Voy un poco tarde.'] },
  { id: 218, languageCode: 'es', lesson: 22, target: 'Estoy llegando.', pronunciation: 'إستوي ييگاندو', english: 'I\'m on my way / I\'m arriving.', answers: ['Estoy llegando.'] },
  { id: 219, languageCode: 'es', lesson: 22, target: 'Espérame cinco minutos.', pronunciation: 'إسبيرامي ثينكو مينوتوس', english: 'Wait for me five minutes.', answers: ['Espérame cinco minutos.'] },
  { id: 220, languageCode: 'es', lesson: 22, target: 'Nos vemos allí.', pronunciation: 'نوس بيموس أيّي', english: 'See you there.', answers: ['Nos vemos allí.'] },
  { id: 221, languageCode: 'es', lesson: 23, target: 'Voy a cocinar algo.', pronunciation: 'بوي آ كوثينار ألغو', english: 'I\'m going to cook something.', answers: ['Voy a cocinar algo.'] },
  { id: 222, languageCode: 'es', lesson: 23, target: '¿Qué quieres comer?', pronunciation: 'كي كييريس كومير', english: 'What do you want to eat?', answers: ['¿Qué quieres comer?'] },
  { id: 223, languageCode: 'es', lesson: 23, target: 'No sé qué cocinar.', pronunciation: 'نو سي كي كوثينار', english: 'I don\'t know what to cook.', answers: ['No sé qué cocinar.'] },
  { id: 224, languageCode: 'es', lesson: 23, target: 'Necesito comprar comida.', pronunciation: 'نيسيسيتو كومبرار كوميدا', english: 'I need to buy food.', answers: ['Necesito comprar comida.'] },
  { id: 225, languageCode: 'es', lesson: 23, target: 'Falta leche.', pronunciation: 'فالطا ليتشي', english: 'We\'re out of milk.', answers: ['Falta leche.'] },
  { id: 226, languageCode: 'es', lesson: 23, target: 'La comida ya está lista.', pronunciation: 'لا كوميدا يا إستا ليستا', english: 'The food is ready.', answers: ['La comida ya está lista.'] },
  { id: 227, languageCode: 'es', lesson: 23, target: 'Pon la comida en la mesa.', pronunciation: 'بون لا كوميدا إن لا ميسا', english: 'Put the food on the table.', answers: ['Pon la comida en la mesa.'] },
  { id: 228, languageCode: 'es', lesson: 23, target: 'Voy a lavar los platos después.', pronunciation: 'بوي آ لابار لوس بلاتوس ديسبويس', english: 'I\'ll wash the dishes later.', answers: ['Voy a lavar los platos después.'] },
  { id: 229, languageCode: 'es', lesson: 23, target: 'Guarda esto en la nevera.', pronunciation: 'غواردَا إستو إن لا نيبيرا', english: 'Put this in the fridge.', answers: ['Guarda esto en la nevera.'] },
  { id: 230, languageCode: 'es', lesson: 23, target: 'No queda nada.', pronunciation: 'نو كيدا نادا', english: 'There\'s nothing left.', answers: ['No queda nada.'] },
  { id: 231, languageCode: 'es', lesson: 24, target: 'Tengo que limpiar el baño.', pronunciation: 'تينغو كي ليمبيار إل بانيو', english: 'I have to clean the bathroom.', answers: ['Tengo que limpiar el baño.'] },
  { id: 232, languageCode: 'es', lesson: 24, target: 'Voy a sacar la basura.', pronunciation: 'بوي آ ساكار لا باسورا', english: 'I\'m going to take out the trash.', answers: ['Voy a sacar la basura.'] },
  { id: 233, languageCode: 'es', lesson: 24, target: '¿Dónde está el detergente?', pronunciation: 'دوندي إستا إل ديترخينتي', english: 'Where is the detergent?', answers: ['¿Dónde está el detergente?'] },
  { id: 234, languageCode: 'es', lesson: 24, target: 'Está todo limpio.', pronunciation: 'إستا تودو ليمبيو', english: 'Everything is clean.', answers: ['Está todo limpio.'] },
  { id: 235, languageCode: 'es', lesson: 24, target: 'Tengo que hacer la cama.', pronunciation: 'تينغو كي أثِر لا كاما', english: 'I have to make the bed.', answers: ['Tengo que hacer la cama.'] },
  { id: 236, languageCode: 'es', lesson: 24, target: 'Voy a ordenar mi escritorio.', pronunciation: 'بوي آ أوردينار مي إسكريتوريو', english: 'I\'m going to organize my desk.', answers: ['Voy a ordenar mi escritorio.'] },
  { id: 237, languageCode: 'es', lesson: 24, target: 'No encuentro mis llaves.', pronunciation: 'نو إنكوينترو ميس يابيس', english: 'I can\'t find my keys.', answers: ['No encuentro mis llaves.'] },
  { id: 238, languageCode: 'es', lesson: 24, target: '¿Has visto mi teléfono?', pronunciation: 'آس بيستو مي تيليفونو', english: 'Have you seen my phone?', answers: ['¿Has visto mi teléfono?'] },
  { id: 239, languageCode: 'es', lesson: 24, target: 'Lo dejé aquí.', pronunciation: 'لو ديخي أكي', english: 'I left it here.', answers: ['Lo dejé aquí.'] },
  { id: 240, languageCode: 'es', lesson: 24, target: 'Ya lo encontré.', pronunciation: 'يا لو إنكونتري', english: 'I found it.', answers: ['Ya lo encontré.'] },
  { id: 241, languageCode: 'es', lesson: 25, target: 'Tengo que hacer los deberes.', pronunciation: 'تينغو كي أثِر لوس ديبيريس', english: 'I have to do my homework.', answers: ['Tengo que hacer los deberes.'] },
  { id: 242, languageCode: 'es', lesson: 25, target: 'Voy a estudiar un poco.', pronunciation: 'بوي آ إستوديار أون بوكو', english: 'I\'m going to study a little.', answers: ['Voy a estudiar un poco.'] },
  { id: 243, languageCode: 'es', lesson: 25, target: '¿Has terminado?', pronunciation: 'آس تيرمينادو', english: 'Have you finished?', answers: ['¿Has terminado?'] },
  { id: 244, languageCode: 'es', lesson: 25, target: 'Todavía no.', pronunciation: 'تودابيا نو', english: 'Not yet.', answers: ['Todavía no.'] },
  { id: 245, languageCode: 'es', lesson: 25, target: 'Ya terminé.', pronunciation: 'يا تيرميني', english: 'I finished.', answers: ['Ya terminé.'] },
  { id: 246, languageCode: 'es', lesson: 25, target: 'No tengo tiempo ahora.', pronunciation: 'نو تينغو تييمبو أورا', english: 'I don\'t have time now.', answers: ['No tengo tiempo ahora.'] },
  { id: 247, languageCode: 'es', lesson: 25, target: 'Te llamo más tarde.', pronunciation: 'تي يامو ماس تاردي', english: 'I\'ll call you later.', answers: ['Te llamo más tarde.'] },
  { id: 248, languageCode: 'es', lesson: 25, target: 'Mándame un mensaje.', pronunciation: 'ماندامي أون مينساخي', english: 'Send me a message.', answers: ['Mándame un mensaje.'] },
  { id: 249, languageCode: 'es', lesson: 25, target: 'Avísame cuando llegues.', pronunciation: 'أبيسامي كواندو ييگيس', english: 'Let me know when you arrive.', answers: ['Avísame cuando llegues.'] },
  { id: 250, languageCode: 'es', lesson: 25, target: 'Nos vemos mañana.', pronunciation: 'نوس بيموس مانيانا', english: 'See you tomorrow.', answers: ['Nos vemos mañana.'] }
];

// Optional friendly titles per lesson number. If a lesson number has no
// entry here, the UI just falls back to "Lesson N" — adding sentences to
// a new lesson number never requires touching this map.
const LESSON_TITLES = {
  1: 'Greetings & Feelings',
  2: 'Morning & Work',
  3: 'Mistakes & Apologies',
  4: 'Opinions & Emotions',
  5: 'Wrapping Up',
  6: 'Morning Routine',
  7: 'Work Time',
  8: 'Tiredness & Evening',
  9: 'Laughing & Daily Chat',
  10: 'Frustration & Mistakes',
  11: 'Daily Conversation',
  12: 'Staying in Touch',
  13: 'Thinking It Over',
  14: 'Opinions & Patience',
  15: 'Reflecting & Moving On',
  16: 'Travel',
  17: 'Studying',
  18: 'Home & Cleaning',
  19: 'Restaurant & Food',
  20: 'Daily Routine',
  21: 'Shopping',
  22: 'Getting Around',
  23: 'Cooking',
  24: 'Cleaning the House',
  25: 'Homework & Messages'
};
